stats-client:
  url: http://localhost:9090

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5433/ewm
    username: ewm
    password: ewm
  jpa:
    hibernate:
      ddl-auto: update

  server:
    port: 8080