services:

  stats-server:
    build: ./stats/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
        - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_CLIENT_URL=http://stats-server:9090

  ewm-db:
     image: postgres:16.1
     container_name: ewm-db
     environment:
       POSTGRES_DB: ewm
       POSTGRES_USER: ewm
       POSTGRES_PASSWORD: ewm
     ports:
       - "5433:5432"